# Generated by Django 5.1.3 on 2024-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_password_alter_buyer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
